---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Toronto
      - CLI_ARGS= #optional
    volumes:
      - /mnt/sharedata/duplicati/appdata/config:/config
      - /mnt/sharedata/backups:/backups
      - /duplicati/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped
